[package]
name = "saas"
version = "0.1.0"
authors = ["johesoman <johesoman@gmail.com>"]
edition = "2018"

[dependencies]
getch = "0.2.1"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

colored = "1.7"

rand = "0.6.5"
